name: Pre Commit

on:
  pull_request:
    paths:
      - '**/*'
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: mise run pre-commit
